In [3]:
import numpy as np

# a. Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch 
A = np.array([[2, -1, 0],
              [1, 1, 1],
              [3, -2, 1]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A) if det_A != 0 else None

# b. Nhập họ và tên hoặc mã số sinh viên
text = "Nguyen Tan Khang"


char_to_num = {chr(i): i - 65 for i in range(65, 91)} 
char_to_num.update({chr(i): i - 71 for i in range(97, 123)})  
char_to_num[' '] = 52


num_to_char = {v: k for k, v in char_to_num.items()}

# c. Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên). 
nums = [char_to_num[char] for char in text if char in char_to_num]


while len(nums) % 3 != 0:
    nums.append(52)

vectors = np.array(nums).reshape(-1, 3).T
encoded = A @ vectors

# d. d. Thực hiện giải mã với ma trận được chọn. 
decoded_vectors = np.round(inv_A @ encoded).astype(int)
decoded_nums = decoded_vectors.T.flatten()
decoded_text = ''.join(num_to_char[n] for n in decoded_nums if n in num_to_char)

A, det_A, inv_A, encoded, decoded_text


(array([[ 2, -1,  0],
        [ 1,  1,  1],
        [ 3, -2,  1]]),
 np.float64(4.0),
 array([[ 0.75,  0.25, -0.25],
        [ 0.5 ,  0.5 , -0.5 ],
        [-1.25,  0.25,  0.75]]),
 array([[ -6,  70,  85,  26,  40,  12],
        [ 91, 119,  97, 101,  98, 136],
        [ 21, 129, 144,  23,  86,  44]]),
 'Nguyen Tan Khang  ')