In [ ]:
#2.1. Nhân ma trận
import numpy as np
nhu_cau = np.array([
    [6, 5, 3, 1],  
    [3, 6, 2, 2], 
    [3, 4, 3, 1]  
])
gia_san_pham = np.array([
    [1.50, 1.00],   
    [2.00, 2.50],  
    [5.00, 4.50],   
    [16.00, 17.00] 
])
tong_tien = nhu_cau @ gia_san_pham
print("Tổng tiền mỗi người nếu mua tại từng siêu thị:")
print("Cột 0: Siêu thị 1 (S1), Cột 1: Siêu thị 2 (S2)")
print(tong_tien)
nguoi = ["Cảnh", "Nhật", "Hiếu"]
for i in range(len(nguoi)):
    print(f"{nguoi[i]} nên mua ở siêu thị ", end="")
    if tong_tien[i, 0] < tong_tien[i, 1]:
        print(f"S1 (Giá: {tong_tien[i, 0]})")
    elif tong_tien[i, 0] > tong_tien[i, 1]:
        print(f"S2 (Giá: {tong_tien[i, 1]})")
    else:
        print(f"S1 hoặc S2 (Giá: {tong_tien[i, 0]}) vì giá bằng nhau")

Tổng tiền mỗi người nếu mua tại từng siêu thị:
Cột 0: Siêu thị 1 (S1), Cột 1: Siêu thị 2 (S2)
[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]
Cảnh nên mua ở siêu thị S2 (Giá: 49.0)
Nhật nên mua ở siêu thị S1 (Giá: 58.5)
Hiếu nên mua ở siêu thị S1 hoặc S2 (Giá: 43.5) vì giá bằng nhau


In [ ]:
#2.3 Ma trận hội tụ 
import numpy as np
A = np.array([[0, 1], [1, 0]])
print("Ma trận A:")
print(A)

temp = A.dot(A)
print("A^2:")
print(temp)

print("Các lũy thừa tiếp theo của A:")
k = 6
for i in range(k - 1):
    temp = temp.dot(A)
    print(f"A^{i+3}:")
    print(temp)
    print('---')
B = np.array([[0, -1], [-1, 0]])
print("Ma trận B:")
print(B)

temp = B.dot(B)
print("B^2:")
print(temp)

print("Các lũy thừa tiếp theo của B:")
k = 5
for i in range(k - 1):
    temp = temp.dot(B)
    print(f"B^{i+3}:")
    print(temp)
    print('---')
C = np.array([
    [1, 0, 0],
    [0, 0.5, 1],
    [0, 0, 0.5]
])
print("Ma trận C:")
print(C)

temp = C.dot(C)
print("C^2:")
print(temp)

k = 1000
for i in range(k - 1):
    temp = temp.dot(C)
print("C^1000:")
print(temp)

for i in range(k - 1):
    temp = temp.dot(C)
print("C^2000:")
print(temp)





Ma trận A:
[[0 1]
 [1 0]]
A^2:
[[1 0]
 [0 1]]
Các lũy thừa tiếp theo của A:
A^3:
[[0 1]
 [1 0]]
---
A^4:
[[1 0]
 [0 1]]
---
A^5:
[[0 1]
 [1 0]]
---
A^6:
[[1 0]
 [0 1]]
---
A^7:
[[0 1]
 [1 0]]
---
Ma trận B:
[[ 0 -1]
 [-1  0]]
B^2:
[[1 0]
 [0 1]]
Các lũy thừa tiếp theo của B:
B^3:
[[ 0 -1]
 [-1  0]]
---
B^4:
[[1 0]
 [0 1]]
---
B^5:
[[ 0 -1]
 [-1  0]]
---
B^6:
[[1 0]
 [0 1]]
---
Ma trận C:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
C^2:
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
C^1000:
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
C^2000:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#2.4. Ma trận Markov
import numpy as np
M = np.array([[0.8, 0.3],
              [0.2, 0.7]])
M2 = M.dot(M)
print("M^2:\n", M2)
M3 = M2.dot(M)
print("M^3:\n", M3)


M^2:
 [[0.7  0.45]
 [0.3  0.55]]
M^3:
 [[0.65  0.525]
 [0.35  0.475]]
