In [1]:
#3.11
import numpy as np
A = np.array([
    [2, 4, 6, 8],
    [1, 3, 5, 7],
    [9, 7, 5, 3]
])
print("Ma trận gốc A:")
print(A)
B = np.random.rand(3, 2)
C = np.linalg.pinv(B) @ A  
print("\nMa trận B:")
print(B)
print("\nMa trận C:")
print(C)
A_reconstructed = B @ C
print("\nMa trận A khôi phục lại (gần đúng):")
print(A_reconstructed)
error = np.abs(A - A_reconstructed)
print("\nSai số tuyệt đối giữa A và A_reconstructed:")
print(error)


Ma trận gốc A:
[[2 4 6 8]
 [1 3 5 7]
 [9 7 5 3]]

Ma trận B:
[[0.16593833 0.02937297]
 [0.8293568  0.2350453 ]
 [0.74358659 0.15202312]]

Ma trận C:
[[  39.34997523   27.62695235   15.90392947    4.1809066 ]
 [-134.41985414  -85.28621272  -36.1525713    12.98107012]]

Ma trận A khôi phục lại (gần đúng):
[[2.58135858 2.07926081 1.57716304 1.07506526]
 [1.040414   2.86647697 4.69253994 6.5186029 ]
 [8.82518875 7.57755545 6.32992214 5.08228883]]

Sai số tuyệt đối giữa A và A_reconstructed:
[[0.58135858 1.92073919 4.42283696 6.92493474]
 [0.040414   0.13352303 0.30746006 0.4813971 ]
 [0.17481125 0.57755545 1.32992214 2.08228883]]


In [5]:
#3.2
import numpy as np
from scipy import linalg

M = np.array([[0.8, 0.3],
              [0.2, 0.7]])
print("Ma trận M ban đầu:")
print(M)

P, L, U = linalg.lu(M)

print("\nMa trận P (ma trận hoán vị):")
print(P)

print("\nMa trận L (tam giác dưới):")
print(L)

print("\nMa trận U (tam giác trên):")
print(U)

reconstructed = L.dot(U)
print("\nTích L.dot(U) (không có P):")
print(reconstructed)

print("\nSo sánh P @ M và L @ U:")
print("P @ M:")
print(P.dot(M))

print("L @ U:")
print(reconstructed)

print("\nKiểm tra tính gần bằng:")
print(np.allclose(P.dot(M), reconstructed))






ModuleNotFoundError: No module named 'scipy'