In [1]:
import numpy as np

# Ma trận truyền tin A
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

print("Ma trận A (truyền trực tiếp):")
print(A)
#
temp = A.dot(A)
print("A^2 (truyền trong 2 bước):")
print(temp)
#
temp = temp.dot(A)
print("A^3 (truyền trong 3 bước):")
print(temp)
#
sumA = A.copy()
temp = A.dot(A)
sumA += temp
temp = temp.dot(A)
sumA += temp

print("Tổng số cách truyền tin trong ≤ 3 bước:")
print(sumA)

Ma trận A (truyền trực tiếp):
[[0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [1 1 0 0]]
A^2 (truyền trong 2 bước):
[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
A^3 (truyền trong 3 bước):
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
Tổng số cách truyền tin trong ≤ 3 bước:
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
