In [11]:
# Import các thư viện cần thiết
from scipy import linalg
import numpy as np

# Khởi tạo mảng và ma trận
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])  # số phức
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])  # ma trận số thực

# Các kiểu khai báo và khởi tạo ma trận
A = np.asmatrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.asmatrix(np.random.random((10, 5)))
D = np.asmatrix([[4, 3], [2, 6]])
F1 = np.eye(3, k=1)  # đường chéo trên đường chéo chính

# Thử với k = 0
F2 = np.eye(3, k=0)
print("F2 =\n", F2)

# Thử với k = -1
F3 = np.eye(3, k=-1)
print("F3 =\n", F3)

# Xem hạng ma trận
print("Rank of matrix C:", np.linalg.matrix_rank(C))

# Tính ma trận nghịch đảo
print("Inverse of A (A.I):", A.I)


F2 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
F3 =
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
Rank of matrix C: 5
Inverse of A (A.I): [[ 1.78184639 -0.59868199]
 [-1.18617223  1.50224399]]
