In [1]:
import numpy as np
from scipy import linalg, sparse

ModuleNotFoundError: No module named 'scipy'

In [2]:
D = np.mat([[3, 4], [5, 6]])
print("Ma trận D:")
print(D)

C = np.mat(np.random.random((5, 7)))
print("Ma trận C (5x7):")
print(C)

A = np.mat(np.random.random((2, 2)))
print("Ma trận A (2x2):")
print(A)

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [3]:
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print("Mảng b:")
print(b)
print("Ma trận B:")
print(B)

print("Chuyển vị của A:")
print(A.T)

print("Nghịch đảo của A:")
print(A.I)
print("Hoặc dùng scipy:")
print(linalg.inv(A))

Mảng b:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Ma trận B:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Chuyển vị của A:


NameError: name 'A' is not defined

In [4]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
print("Ma trận M:")
print(M)

print("Ma trận dưới đường chéo:")
print(np.tril(M))

print("Ma trận trên đường chéo:")
print(np.triu(M))

v_diag = np.diag(M)
print("Vector đường chéo:")
print(v_diag)

M_diag = np.diag(v_diag)
print("Ma trận đường chéo:")
print(M_diag)

Ma trận M:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]
Ma trận dưới đường chéo:
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
Ma trận trên đường chéo:
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
Vector đường chéo:
[-1 -2 -2]
Ma trận đường chéo:
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [5]:
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

I6 = np.identity(6)
print("Ma trận đơn vị I6:")
print(I6)

print("Kích thước A:", A.size)
print("Đường chéo của A:", A.diagonal())

A = A + I6
print("Ma trận A sau khi cộng I6:")
print(A)

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Kích thước A: 36
Đường chéo của A: [ 0.  7. 14. 21. 28. 35.]
Ma trận A sau khi cộng I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [6]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("Tích A.dot(vecB):")
print(C)

D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("Ma trận D:")
print(D)
E = A.dot(D.T)
print("Tích A.dot(D.T):")
print(E)

F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
print("Ma trận F:")
print(F)
G = A.dot(F)
print("Tích A.dot(F):")
print(G)

Tích A.dot(vecB):
[ 71. 198. 325. 452. 579. 706.]
Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
Tích A.dot(D.T):
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
Tích A.dot(F):
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [7]:
invA = np.linalg.inv(A)
print("Nghịch đảo của A:")
print(invA)

print("np.linalg.inv(np.linalg.inv(A)):")
print(np.linalg.inv(invA))

Nghịch đảo của A:
[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]
np.linalg.inv(np.linalg.inv(A)):
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
