In [1]:
import numpy as np
from numpy.linalg import matrix_power, inv

# Phần 1: Markov - Sau 100 tuần
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([[0.95], [0.05]])
A100 = matrix_power(A, 100)
v100 = A100 @ v0
print("Trạng thái sau 100 tuần (làm việc, thất nghiệp):")
print(v100)

Trạng thái sau 100 tuần (làm việc, thất nghiệp):
[[0.98550723]
 [0.01449277]]


In [7]:
# Ô 1: Import thư viện
import sympy as sym

# Ô 2: Khai báo biến và biểu thức
x, y = sym.symbols('x y')

# Tạo hệ phương trình (dùng Rational để tránh sai số)
eq1 = sym.Eq(sym.Rational(-2, 1000)*x + sym.Rational(136, 1000)*y, 0)
eq2 = sym.Eq(x + y, 1)

# Ô 3: Giải hệ phương trình
nghiem = sym.solve([eq1, eq2], (x, y))

# Ô 4: Hiển thị kết quả
print("Trạng thái cân bằng:")
sym.pprint(nghiem)

# In thêm dạng thập phân
print("\nKết quả dưới dạng số thập phân:")
print(f"x = {sym.N(nghiem[x])} (có việc làm)")
print(f"y = {sym.N(nghiem[y])} (thất nghiệp)")


ModuleNotFoundError: No module named 'sympy'

In [3]:
A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1/3, 3], [1, 1]])
P_inv = inv(P)
A_check = P @ D @ P_inv
print("A tái tạo lại từ chéo hóa:")
print(np.round(A_check, 4))

D_power = np.linalg.matrix_power(D, 1000)
A_power = P @ D_power @ P_inv
print("A^1000 (tính bằng chéo hóa):")
print(np.round(A_power, 4))

A tái tạo lại từ chéo hóa:
[[ 2.  3.]
 [ 3. -6.]]
A^1000 (tính bằng chéo hóa):
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
